{
 "title": "Waterdog RakNet",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Bandwidth",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "rate(bytesOut{job=\"bungee\"}[1m]) * 8",
     "legendFormat": "Out"
    },
    {
     "expr": "rate(bytesRecalled{job=\"bungee\"}[1m]) * 8",
     "legendFormat": "Resend Out"
    },
    {
     "expr": "rate(bytesIn{job=\"bungee\"}[1m]) * 8",
     "legendFormat": "In"
    }
   ]
  },
  {
   "title": "Resend Ratios",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(rate(bytesRecalled{job=\"bungee\"}[1m]) - rate(bytesNACKd{job=\"bungee\"}[1m])) / rate(bytesOut{job=\"bungee\"}[1m])",
     "legendFormat": "Timed Resend"
    },
    {
     "expr": "(rate(bytesNACKd{job=\"bungee\"}[1m])) / rate(bytesOut{job=\"bungee\"}[1m])",
     "legendFormat": "NACK Resend"
    }
   ]
  },
  {
   "title": "Output RakNet Metrics",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short", "label": "pps" }
   ],
   "targets": [
    {
     "expr": "rate(framesOut{job=\"bungee\"}[1m])",
     "legendFormat": "Frames Out"
    },
    {
     "expr": "rate(packetsOut{job=\"bungee\"}[1m])",
     "legendFormat": "FrameSets Out"
    }
   ]
  },
  {
   "title": "Burst Token Histogram",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(burstTokens_bucket[1m])) by (le)) * 1000",
     "legendFormat": "99th"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(burstTokens_bucket[1m])) by (le)) * 1000",
     "legendFormat": "95th"
    },
    {
     "expr": "histogram_quantile(0.80, sum(rate(burstTokens_bucket[1m])) by (le)) * 1000",
     "legendFormat": "80th"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(burstTokens_bucket[1m])) by (le)) * 1000",
     "legendFormat": "50th"
    },
    {
     "expr": "rate(burstTokens_sum[1m]) / rate(burstTokens_count[1m]) * 1000",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Input RakNet Metrics",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "pps" }
   ],
   "targets": [
    {
     "expr": "rate(framesIn{job=\"bungee\"}[1m])",
     "legendFormat": "Frames In"
    },
    {
     "expr": "rate(packetsIn{job=\"bungee\"}[1m])",
     "legendFormat": "FrameSets In"
    },
    {
     "expr": "rate(nacksSent{job=\"bungee\"}[1m])",
     "legendFormat": "NACK'd FrameSets"
    }
   ]
  },
  {
   "title": "RTT Histogram",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(rtt_bucket[1m])) by (le)) * 1000",
     "legendFormat": "99th"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(rtt_bucket[1m])) by (le)) * 1000",
     "legendFormat": "95th"
    },
    {
     "expr": "histogram_quantile(0.80, sum(rate(rtt_bucket[1m])) by (le)) * 1000",
     "legendFormat": "80th"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(rtt_bucket[1m])) by (le)) * 1000",
     "legendFormat": "50th"
    },
    {
     "expr": "rate(rtt_sum[1m]) / rate(rtt_count[1m]) * 1000",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Compression",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1.0 - rate(out_post_comp{job=\"bungee\"}[1m]) / rate(out_pre_comp{job=\"bungee\"}[1m])",
     "legendFormat": "Data Reduction (higher is better)"
    }
   ]
  }
 ]
}